services:
  #postgres database
  db:
    restart: on-failure
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 8001:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  rest_app:
    build: .
    container_name: rest_container
    restart: always
    volumes:
      - .:/django
      - staticfiles:/django/staticfiles
      - media:/django/mediafiles
    ports:
      - 8000:8000
    image: python:3.11-slim-buster
    command: gunicorn rest_project.wsgi --bind 0.0.0.0:8000  --timeout 1800
    depends_on:
      - db

  #nginx server docker image
  nginx:
    restart: on-failure
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles
      - media:/mediafiles
    ports:
      - 80:80
    depends_on:
      - rest_app

  #elasticsearch configuration 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    restart: on-failure
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  staticfiles:
  media:
  elasticsearch-data:
  db: