# Generated by Django 4.1.7 on 2023-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/products/original')),
                ('thumbnail', models.ImageField(null=True, upload_to='images/products/thumbnail')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
